// Copyright https://github.com/MothCocoon/FlowGraph/graphs/contributors

#pragma once

#include "Nodes/FlowPin.h"

#if WITH_EDITOR

class UFlowNode;
class UObject;
struct FFlowDataPinValue;

// Container for pin data collected during automatic pin generation
struct FFlowPinSourceData
{
	FFlowPinSourceData(const FFlowPin& InFlowPin, const FName& InPropertyOwnerObjectName, int32 InPropertyOwnerIndex = 0, const FFlowDataPinValue* InDataPinValue = nullptr)
		: FlowPin(InFlowPin)
		, PropertyOwnerObjectName(InPropertyOwnerObjectName)
		, PropertyOwnerIndex(InPropertyOwnerIndex)
		, DataPinValue(InDataPinValue)
	{
	}

	FFlowPin FlowPin;
	FName PropertyOwnerObjectName;
	int32 PropertyOwnerIndex = INDEX_NONE;
	const FFlowDataPinValue* DataPinValue = nullptr;
};

// Transient working data used during auto-generation of data pins
struct FFlowAutoDataPinsWorkingData
{
public:
	FFlowAutoDataPinsWorkingData(const TArray<FFlowPin>& InputPinsPrev, const TArray<FFlowPin>& OutputPinsPrev)
		: AutoInputDataPinsPrev(InputPinsPrev)
		, AutoOutputDataPinsPrev(OutputPinsPrev)
	{
	}

	FLOW_API bool AutoGenerateDataPinsForFlowNode(UFlowNode& FlowNode, bool& bAutoInputDataPinsChanged, bool& bAutoOutputDataPinsChanged);

	FLOW_API void AddFlowDataPinsForClassProperties(const UObject& ObjectContainer, int32 PropertyOwnerIndex);

	FLOW_API static void BuildNextFlowPinArray(const TArray<FFlowPinSourceData>& PinSourceDatas, TArray<FFlowPin>& OutFlowPins);

protected:
	void DisambiguateAndRebuildDataPinPropertySourceMap(UFlowNode& FlowNode);
	void AddInputDataPinsToMap(UFlowNode& FlowNode);
	void AddOutputDataPinsToMap(UFlowNode& FlowNode);
	void AddFlowDataPinForProperty(const FProperty* Property, const UObject& ObjectContainer, int32 PropertyOwnerIndex);

	void AddPinMappingToNode(
		UFlowNode& FlowNode,
		const FName& FinalPinName,
		const FName& OriginalPinName,
		int32 PropertyOwnerIndex);

	bool DidAutoInputDataPinsChange() const;
	bool DidAutoOutputDataPinsChange() const;

	static void DisambiguateDuplicateOutputDataPin(
		FFlowPinSourceData& PinSourceData,
		TSet<FName>& InOutUsedNames,
		uint32 LogicalDuplicateIndex);

	static bool CheckIfProposedPinsMatchPreviousPins(const TArray<FFlowPin>& PrevPins, const TArray<FFlowPinSourceData>& ProposedPins);

public:
	const TArray<FFlowPin>& AutoInputDataPinsPrev;
	const TArray<FFlowPin>& AutoOutputDataPinsPrev;

	TArray<FFlowPinSourceData> AutoInputDataPinsNext;
	TArray<FFlowPinSourceData> AutoOutputDataPinsNext;
};

#endif