// Copyright https://github.com/MothCocoon/FlowGraph/graphs/contributors

#pragma once

#include "Nodes/FlowPin.h"

// Working Data struct for the UFlowDataPinGeneratorNodeInterface::AutoGenerateDataPins function
struct FFlowAutoDataPinsWorkingData
{
	FFlowAutoDataPinsWorkingData(const TArray<FFlowPin>& InputPinsPrev, const TArray<FFlowPin>& OutputPinsPrev)
		: AutoInputDataPinsPrev(InputPinsPrev)
		, AutoOutputDataPinsPrev(OutputPinsPrev)
		{ }

#if WITH_EDITOR
	FLOW_API void AddFlowDataPinsForClassProperties(const UObject& ObjectContainer);
	FLOW_API void AddFlowDataPinForProperty(const FProperty* Property, const UObject& ObjectContainer);

	FLOW_API bool DidAutoInputDataPinsChange() const;
	FLOW_API bool DidAutoOutputDataPinsChange() const;
#endif

	const TArray<FFlowPin>& AutoInputDataPinsPrev;
	const TArray<FFlowPin>& AutoOutputDataPinsPrev;
	
	TArray<FFlowPin> AutoInputDataPinsNext;
	TArray<FFlowPin> AutoOutputDataPinsNext;
};
