// Copyright https://github.com/MothCocoon/FlowGraph/graphs/contributors

#include "Nodes/Graph/FlowNode_SetGraphOutput.h"

#include "FlowAsset.h"
#include "Types/FlowDataPinResults.h"
#include "Types/FlowNamedDataPinProperty.h"

#if WITH_EDITOR
#include "Types/FlowAutoDataPinsWorkingData.h"
#endif

#include UE_INLINE_GENERATED_CPP_BY_NAME(FlowNode_SetGraphOutput)

UFlowNode_SetGraphOutput::UFlowNode_SetGraphOutput()
{
#if WITH_EDITOR
	Category = TEXT("Graph");
	NodeDisplayStyle = FlowNodeStyle::InOut;
#endif

	AllowedSignalModes = {EFlowSignalMode::Enabled, EFlowSignalMode::Disabled};
}

void UFlowNode_SetGraphOutput::ExecuteInput(const FName& PinName)
{
	CommitOutputDataPinValues();

	TriggerFirstOutput(true);
}

void UFlowNode_SetGraphOutput::CommitOutputDataPinValues()
{
	UFlowAsset* FlowAsset = GetFlowAsset();
	if (!IsValid(FlowAsset))
	{
		return;
	}

	const UFlowAsset* TemplateAsset = FlowAsset->GetTemplateAsset();
	if (!IsValid(TemplateAsset))
	{
		return;
	}

	bool bNeedsFlush = false;

	for (const FFlowNamedDataPinProperty& Declaration : TemplateAsset->GetOutputDataPinDeclarations())
	{
		if (!Declaration.IsValid())
		{
			continue;
		}

		if (!IsInputConnected(Declaration.Name))
		{
			continue;
		}

		const FFlowDataPinResult PinResult = TryResolveDataPin_SetGraphOutputAccess(Declaration.Name);
		if (PinResult.Result == EFlowDataPinResolveResult::Success)
		{
			bNeedsFlush = true;

			FlowAsset->WriteOutputDataPinValue(Declaration.Name, PinResult.ResultValue);
		}
	}

	if (bNeedsFlush)
	{
		FlowAsset->FlushOutputDataPinValuesToReceiver();
	}
}

#if WITH_EDITOR
bool UFlowNode_SetGraphOutput::SupportsContextPins() const
{
	const UFlowAsset* FlowAsset = GetFlowAsset();
	if (IsValid(FlowAsset) && !FlowAsset->GetOutputDataPinDeclarations().IsEmpty())
	{
		return true;
	}

	return Super::SupportsContextPins();
}

void UFlowNode_SetGraphOutput::AutoGenerateDataPins(FFlowDataPinValueOwner& ValueOwner, FFlowAutoDataPinsWorkingData& InOutWorkingData)
{
	Super::AutoGenerateDataPins(ValueOwner, InOutWorkingData);

	const UFlowAsset* FlowAsset = GetFlowAsset();
	if (!IsValid(FlowAsset))
	{
		return;
	}

	for (FFlowNamedDataPinProperty DeclarationCopy : FlowAsset->GetOutputDataPinDeclarations())
	{
		if (!DeclarationCopy.IsValid())
		{
			continue;
		}

		if (DeclarationCopy.DataPinValue.IsValid())
		{
			FFlowDataPinValue& Value = DeclarationCopy.DataPinValue.GetMutable<FFlowDataPinValue>();
			Value.bIsInputPin = true;
		}

		DeclarationCopy.AutoGenerateDataPinForProperty(ValueOwner, InOutWorkingData);
	}
}
#endif
