// Copyright https://github.com/MothCocoon/FlowGraph/graphs/contributors
#pragma once

#include "Nodes/FlowNode.h"
#include "FlowNode_SetGraphOutput.generated.h"

/**
 * Resolves connected input data pins from the Flow Asset's OutputDataPinDeclarations and
 * writes their values to the asset's output data store. Functions as a pass-through exec node.
 * UFlowNode_Finish derives from this class and additionally finishes the graph.
 */
UCLASS(NotBlueprintable, meta = (DisplayName = "Set Graph Output"))
class FLOW_API UFlowNode_SetGraphOutput : public UFlowNode
{
	GENERATED_BODY()

public:
	UFlowNode_SetGraphOutput();

protected:
	virtual void ExecuteInput(const FName& PinName) override;

	/* Resolve all connected input data pins and write them to the Flow Asset's output store. */
	void CommitOutputDataPinValues();

#if WITH_EDITOR
	// IFlowContextPinSupplierInterface
	virtual bool SupportsContextPins() const override;
	// --

	// IFlowDataPinValueOwnerInterface
	virtual void AutoGenerateDataPins(FFlowDataPinValueOwner& ValueOwner, FFlowAutoDataPinsWorkingData& InOutWorkingData) override;
	// --
#endif
};
