// Copyright https://github.com/MothCocoon/FlowGraph/graphs/contributors
#pragma once

#include "Interfaces/FlowGraphOutputDataReceiverInterface.h"
#include "Interfaces/FlowPreloadableInterface.h"
#include "Nodes/FlowNode.h"
#include "Types/FlowDataPinValue.h"
#include "Types/FlowOutputDataPinValues.h"
#include "StructUtils/InstancedStruct.h"
#include "FlowNode_SubGraph.generated.h"

class UFlowAssetParams;

/**
 * Instantiates a child Flow Asset and runs it inline.
 *
 * Fires its Start pin on the child asset and waits for the child to Finish before firing its own output.
 * Custom Input/Output nodes in the child asset add matching pins to this node.
 * Use to compose complex flows from reusable sub-graphs.
 */
UCLASS(NotBlueprintable, meta = (DisplayName = "Sub Graph", Keywords = "subgraph"))
class FLOW_API UFlowNode_SubGraph
	: public UFlowNode
	, public IFlowPreloadableInterface
	, public IFlowGraphOutputDataReceiverInterface
{
	GENERATED_BODY()

public:
	UFlowNode_SubGraph();

	friend class UFlowAsset;
	friend class FFlowNode_SubGraphDetails;
	friend class UFlowSubsystem;

	static FFlowPin StartPin;
	static FFlowPin FinishPin;

protected:
	/* The Flow Asset to instantiate and run as a child graph. */
	UPROPERTY(EditAnywhere, Category = "Graph")
	TSoftObjectPtr<UFlowAsset> Asset;

	/* Flow Asset Params to use as the data pin value supplier for the Asset. */
	UPROPERTY(EditAnywhere, Category = "Graph", meta = (DefaultForInputFlowPin, FlowPinType = "Object"))
	TSoftObjectPtr<UFlowAssetParams> AssetParams;

	/* Allow creating an instance of the same Flow Asset as the one containing this node.
	 * Warning: enabling this can cause infinite recursion if the graph spawns itself unconditionally. */
	UPROPERTY(EditAnywhere, Category = "Graph")
	bool bCanInstanceIdenticalAsset = false;

	UPROPERTY(SaveGame)
	FString SavedAssetInstanceName;

	/* Cached output data pin values received from the inner Flow Asset when it finishes.
	 * Note - Not saved "yet", but should decide if we should include the
	 *        cached output values in the save state. */
	UPROPERTY(Transient)
	FFlowOutputDataPinValues CachedOutputDataPinValues;

protected:
	// IFlowGraphOutputDataReceiverInterface
	virtual void ReceiveOutputDataSnapshot(const FFlowOutputDataPinValues& Snapshot) override;
	// --

	virtual bool CanBeAssetInstanced() const;

public:
	// IFlowPreloadableInterface
	virtual EFlowPreloadResult PreloadContent() override;
	virtual void FlushContent() override;
	// --

	virtual void ExecuteInput(const FName& PinName) override;
	virtual void Cleanup() override;
	virtual void DeinitializeInstance() override;

public:
	virtual void ForceFinishNode() override;

	virtual void OnLoad_Implementation() override;

protected:
	// IFlowDataPinValueSupplierInterface
	virtual FFlowDataPinResult TrySupplyDataPin(const FName PinName) const override;
	// --

#if WITH_EDITORONLY_DATA
protected:
	/* All the classes allowed to be used as assets on this subgraph node. */
	UPROPERTY()
	TArray<TSubclassOf<UFlowAsset>> AllowedAssignedAssetClasses;

	/* All the classes disallowed to be used as assets on this subgraph node. */
	UPROPERTY()
	TArray<TSubclassOf<UFlowAsset>> DeniedAssignedAssetClasses;
#endif

#if WITH_EDITOR
public:
	/**
	 * Assigns the child asset directly, for tooling that generates a sub-graph rather than going through
	 * the details panel. Subscribes to the asset so an interface change still reconstructs this node.
	 */
	void SetAsset(UFlowAsset* InAsset)
	{
		Asset = InAsset;
		SubscribeToAssetChanges();
	}

	virtual FText K2_GetNodeTitle_Implementation() const override;
	virtual FString GetNodeDescription() const override;
	virtual UObject* GetAssetToEdit() override;
	virtual const FFlowAgentDoc& GetAgentDoc() const override;

protected:
	virtual EDataValidationResult ValidateNode() override;

public:
	// IFlowContextPinSupplierInterface
	virtual bool SupportsContextPins() const override { return true; }
	virtual TArray<FFlowPin> GetContextInputs() const override;
	virtual TArray<FFlowPin> GetContextOutputs() const override;
	// --

	// IFlowDataPinValueOwnerInterface
	virtual void AutoGenerateDataPins(FFlowDataPinValueOwner& ValueOwner, FFlowAutoDataPinsWorkingData& InOutWorkingData) override;
	// --

	// UObject
	virtual void PostLoad() override;
	virtual void PreEditChange(FProperty* PropertyAboutToChange) override;
	virtual void PostEditChangeProperty(FPropertyChangedEvent& PropertyChangedEvent) override;
	// --

private:
	void SubscribeToAssetChanges();
#endif

	static const FName AssetParams_MemberName;
};
