// Copyright https://github.com/MothCocoon/FlowGraph/graphs/contributors

#include "Interfaces/FlowDataPinValueOwnerInterface.h"
#include "Interfaces/FlowNamedPropertiesSupplierInterface.h"
#include "Types/FlowAutoDataPinsWorkingData.h"
#include "Types/FlowNamedDataPinProperty.h"

#if WITH_EDITOR
void IFlowDataPinValueOwnerInterface::AutoGenerateDataPins(FFlowDataPinValueOwner& ValueOwner, FFlowAutoDataPinsWorkingData& InOutWorkingData)
{
	// Generate the auto-pins for class properties (ie, FFlowDataPinValue subclasses)
	InOutWorkingData.AddFlowDataPinsForClassProperties(ValueOwner);

	// Generate the auto-pins for named property suppliers' pins (ie, TArray<FFlowNamedDataPinProperty>)
	if (IFlowNamedPropertiesSupplierInterface* NamedPropertySupplier = Cast<IFlowNamedPropertiesSupplierInterface>(ValueOwner.GetValueOwnerAsObject()))
	{
		TArray<FFlowNamedDataPinProperty>& NamedProperties = NamedPropertySupplier->GetMutableNamedProperties();
		for (FFlowNamedDataPinProperty& DataPinProperty : NamedProperties)
		{
			DataPinProperty.AutoGenerateDataPinForProperty(ValueOwner, InOutWorkingData);
		}
	}

	// Subclasses may want to also include additional properties (eg, FFlowNamedDataPinProperty)
}
#endif

bool IFlowDataPinValueOwnerInterface::TryFindPropertyByPinName(
	const FName& PinName,
	const FProperty*& OutFoundProperty,
	TInstancedStruct<FFlowDataPinValue>& OutFoundInstancedStruct) const
{
	const UObject* ThisAsObject = Cast<UObject>(this);
	return TryFindPropertyByPinName_Static(*ThisAsObject, PinName, OutFoundProperty, OutFoundInstancedStruct);
}

bool IFlowDataPinValueOwnerInterface::TryFindPropertyByPinName_Static(const UObject& PropertyOwnerObject, const FName& PinName, const FProperty*& OutFoundProperty, TInstancedStruct<FFlowDataPinValue>& OutFoundInstancedStruct)
{
	// First check if the PinName matches a NamedProperties array name
	if (const IFlowNamedPropertiesSupplierInterface* NamedPropertySupplier = Cast<IFlowNamedPropertiesSupplierInterface>(&PropertyOwnerObject))
	{
		const TArray<FFlowNamedDataPinProperty>& NamedProperties = NamedPropertySupplier->GetNamedProperties();
		for (const FFlowNamedDataPinProperty& NamedProperty : NamedProperties)
		{
			if (NamedProperty.Name == PinName && NamedProperty.IsValid())
			{
				OutFoundInstancedStruct = NamedProperty.DataPinValue;

				return true;
			}
		}
	}

	// Try direct property match
	OutFoundProperty = PropertyOwnerObject.GetClass()->FindPropertyByName(PinName);
	if (OutFoundProperty)
	{
		const FStructProperty* StructProperty = CastField<FStructProperty>(OutFoundProperty);
		if (StructProperty && StructProperty->Struct->IsChildOf(FFlowDataPinValue::StaticStruct()))
		{
			// Initialize to match property's struct
			OutFoundInstancedStruct.InitializeAsScriptStruct(StructProperty->Struct);

			StructProperty->GetValue_InContainer(&PropertyOwnerObject, OutFoundInstancedStruct.GetMutableMemory());
			return true;
		}

		// Raw property (e.g., bool, TArray<bool>) is valid
		check(OutFoundProperty != nullptr);
		return true;
	}

	return false;
}