// Copyright https://github.com/MothCocoon/FlowGraph/graphs/contributors

#include "Types/FlowAutoDataPinsWorkingData.h"
#include "FlowLogChannels.h"
#include "Nodes/FlowNode.h"
#include "Types/FlowDataPinValue.h"
#include "Types/FlowStructUtils.h"

#if WITH_EDITOR

bool FFlowAutoDataPinsWorkingData::AutoGenerateDataPinsForFlowNode(UFlowNode& FlowNode, bool& bAutoInputDataPinsChanged, bool& bAutoOutputDataPinsChanged)
{
	// Allow the node to auto-generate data pins
	FlowNode.AutoGenerateDataPins(*this);

	DisambiguateAndRebuildDataPinPropertySourceMap(FlowNode);

	bAutoInputDataPinsChanged = DidAutoInputDataPinsChange();
	bAutoOutputDataPinsChanged = DidAutoOutputDataPinsChange();

	// Return true if any of the data pins changed
	return bAutoInputDataPinsChanged || bAutoOutputDataPinsChanged;
}

bool FFlowAutoDataPinsWorkingData::DidAutoInputDataPinsChange() const
{
	return !CheckIfProposedPinsMatchPreviousPins(AutoInputDataPinsPrev, AutoInputDataPinsNext);
}

bool FFlowAutoDataPinsWorkingData::DidAutoOutputDataPinsChange() const
{
	return !CheckIfProposedPinsMatchPreviousPins(AutoOutputDataPinsPrev, AutoOutputDataPinsNext);
}

bool FFlowAutoDataPinsWorkingData::CheckIfProposedPinsMatchPreviousPins(const TArray<FFlowPin>& PrevPins, const TArray<FFlowPinSourceData>& ProposedPins)
{
	if (PrevPins.Num() != ProposedPins.Num())
	{
		return false;
	}

	for (int32 Index = 0; Index < PrevPins.Num(); ++Index)
	{
		if (!PrevPins[Index].DeepIsEqual(ProposedPins[Index].FlowPin))
		{
			return false;
		}
	}

	return true;
}

void FFlowAutoDataPinsWorkingData::BuildNextFlowPinArray(const TArray<FFlowPinSourceData>& PinSourceDatas, TArray<FFlowPin>& OutFlowPins)
{
	OutFlowPins.Reset();

	for (const FFlowPinSourceData& PinSourceData : PinSourceDatas)
	{
		OutFlowPins.Add(PinSourceData.FlowPin);
	}
}

void FFlowAutoDataPinsWorkingData::AddFlowDataPinsForClassProperties(const UObject& ObjectContainer, int32 PropertyOwnerIndex)
{
	// Try to harvest pins to auto-generate and/or bind to for each property in the flow node
	UClass* Class = ObjectContainer.GetClass();
	for (TFieldIterator<FProperty> PropertyIt(Class); PropertyIt; ++PropertyIt)
	{
		AddFlowDataPinForProperty(*PropertyIt, ObjectContainer, PropertyOwnerIndex);
	}
}

void FFlowAutoDataPinsWorkingData::AddFlowDataPinForProperty(const FProperty* Property, const UObject& ObjectContainer, int32 PropertyOwnerIndex)
{
	bool bIsInputPin = false;

	const FString* AutoPinType = nullptr;
	const FString* SourceForOutputFlowPinName = nullptr;
	const FString* DefaultForInputFlowPinName = nullptr;

	const void* Container = &ObjectContainer;

	const FStructProperty* StructProperty = CastField<FStructProperty>(Property);
	const FFlowDataPinValue* DataPinValue = nullptr;
	if (StructProperty && StructProperty->Struct)
	{
		const UScriptStruct* ScriptStruct = StructProperty->Struct;

		AutoPinType = ScriptStruct->FindMetaData(FFlowPin::MetadataKey_FlowPinType);
		SourceForOutputFlowPinName = ScriptStruct->FindMetaData(FFlowPin::MetadataKey_SourceForOutputFlowPin);
		DefaultForInputFlowPinName = ScriptStruct->FindMetaData(FFlowPin::MetadataKey_DefaultForInputFlowPin);

		// For blueprint use, we allow the Value structs to set input pins via editor-only data
		DataPinValue = FlowStructUtils::CastStructValue<FFlowDataPinValue>(StructProperty, Container);
		if (DataPinValue)
		{
			bIsInputPin = DataPinValue->IsInputPin();
		}
	}

	if (!AutoPinType)
	{
		AutoPinType = Property->FindMetaData(FFlowPin::MetadataKey_FlowPinType);

		if (!AutoPinType)
		{
			return;
		}
	}

	const FFlowPinType* FlowPinType = FFlowPinType::LookupPinType(FFlowPinTypeName(*AutoPinType));
	if (!FlowPinType)
	{
		UE_LOG(LogFlow, Error, TEXT("Unknown pin type %s for property %s"), **AutoPinType, *Property->GetName());

		return;
	}

	if (!SourceForOutputFlowPinName)
	{
		SourceForOutputFlowPinName = Property->FindMetaData(FFlowPin::MetadataKey_SourceForOutputFlowPin);
	}

	if (!DefaultForInputFlowPinName)
	{
		DefaultForInputFlowPinName = Property->FindMetaData(FFlowPin::MetadataKey_DefaultForInputFlowPin);
	}

	if (SourceForOutputFlowPinName && DefaultForInputFlowPinName)
	{
		UE_LOG(LogFlow, Error, TEXT("Error.  A property cannot be both a %s and %s"),
		       *FFlowPin::MetadataKey_SourceForOutputFlowPin.ToString(),
		       *FFlowPin::MetadataKey_DefaultForInputFlowPin.ToString());

		return;
	}

	bIsInputPin = bIsInputPin || DefaultForInputFlowPinName != nullptr;

	// Default assumption is the pin will be an output pin, unless metadata specifies otherwise
	TArray<FFlowPinSourceData>* FlowPinArray = bIsInputPin ? &AutoInputDataPinsNext : &AutoOutputDataPinsNext;

	// Create the new FlowPin
	FFlowPin NewFlowPin = FlowPinType->CreateFlowPinFromProperty(*Property, Container);

	// Potentially override the PinFriendlyName if the metadata specified an alternative
	if (DefaultForInputFlowPinName)
	{
		const FString SpecifyInputPinNameString = *DefaultForInputFlowPinName;
		if (SpecifyInputPinNameString.Len() > 0)
		{
			NewFlowPin.PinFriendlyName = FText::FromString(SpecifyInputPinNameString);
		}
	}
	else if (SourceForOutputFlowPinName)
	{
		const FString SpecifyOutputPinNameString = *SourceForOutputFlowPinName;
		if (SpecifyOutputPinNameString.Len() > 0)
		{
			NewFlowPin.PinFriendlyName = FText::FromString(SpecifyOutputPinNameString);
		}
	}

	const FName PropertyOwnerObjectName = ObjectContainer.GetFName();
	FlowPinArray->Add(FFlowPinSourceData(NewFlowPin, PropertyOwnerObjectName, PropertyOwnerIndex, DataPinValue));

	if (DataPinValue)
	{
		// Store the PropertyPinName in the property, for blueprint lookup functions.
		DataPinValue->PropertyPinName = NewFlowPin.PinName;
	}
}

void FFlowAutoDataPinsWorkingData::DisambiguateAndRebuildDataPinPropertySourceMap(UFlowNode& FlowNode)
{
	FlowNode.MapDataPinNameToPropertySource.Reset();

	AddInputDataPinsToMap(FlowNode);
	AddOutputDataPinsToMap(FlowNode);
}

void FFlowAutoDataPinsWorkingData::AddInputDataPinsToMap(UFlowNode& FlowNode)
{
	for (const FFlowPinSourceData& PinSource : AutoInputDataPinsNext)
	{
		if (PinSource.FlowPin.IsExecPin())
		{
			continue;
		}

		if (PinSource.PropertyOwnerIndex == 0)
		{
			// default owner is inferred at runtime
			continue;
		}

		AddPinMappingToNode(
			FlowNode,
			PinSource.FlowPin.PinName,
			PinSource.FlowPin.PinName,
			PinSource.PropertyOwnerIndex);
	}
}

void FFlowAutoDataPinsWorkingData::AddOutputDataPinsToMap(UFlowNode& FlowNode)
{
	if (AutoOutputDataPinsNext.IsEmpty())
	{
		return;
	}

	// Group output pins by their original/base name to detect duplicates
	TMap<FName, TArray<int32>> MapPinNameToNextPinIndices;
	for (int32 Idx = 0; Idx < AutoOutputDataPinsNext.Num(); ++Idx)
	{
		const FFlowPinSourceData& Pin = AutoOutputDataPinsNext[Idx];

		const bool bIsDataPin = !Pin.FlowPin.IsExecPin();
		if (bIsDataPin)
		{
			TArray<int32>& UseCountArray = MapPinNameToNextPinIndices.FindOrAdd(Pin.FlowPin.PinName);
			UseCountArray.Add(Idx);
		}
	}

	// Collect names that will remain unchanged (for collision avoidance during renaming)
	TSet<FName> ReservedFinalNames;
	for (const auto& KV : MapPinNameToNextPinIndices)
	{
		const TArray<int32>& Indices = KV.Value;
		if (Indices.Num() == 1)
		{
			const int32 Idx = Indices[0];
			ReservedFinalNames.Add(AutoOutputDataPinsNext[Idx].FlowPin.PinName);
		}
	}

	// Process each group: map unique pins, rename and map duplicates
	for (const auto& KV : MapPinNameToNextPinIndices)
	{
		const TArray<int32>& Indices = KV.Value;
		if (Indices.Num() == 1)
		{
			const int32 Idx = Indices[0];
			const FFlowPinSourceData& Pin = AutoOutputDataPinsNext[Idx];

			const bool bCanOmitPropertyFromMap = Pin.PropertyOwnerIndex == 0;
			if (!bCanOmitPropertyFromMap)
			{
				AddPinMappingToNode(
					FlowNode,
					Pin.FlowPin.PinName,
					Pin.FlowPin.PinName,
					Pin.PropertyOwnerIndex);
			}

			continue;
		}

		// Handle duplicate names — assign unique suffixes
		TSet<FName> UsedNames = ReservedFinalNames;

		// 1-based for user-facing display
		uint32 LogicalDuplicateIndex = 1;

		for (int32 Idx : Indices)
		{
			FFlowPinSourceData& Pin = AutoOutputDataPinsNext[Idx];
			const FName OriginalName = Pin.FlowPin.PinName;

			DisambiguateDuplicateOutputDataPin(Pin, UsedNames, LogicalDuplicateIndex);

			const FName& DisambiguatedName = Pin.FlowPin.PinName;
			AddPinMappingToNode(
				FlowNode,
				DisambiguatedName,
				OriginalName,
				Pin.PropertyOwnerIndex);

			++LogicalDuplicateIndex;
		}
	}
}

void FFlowAutoDataPinsWorkingData::AddPinMappingToNode(
	UFlowNode& FlowNode,
	const FName& FinalPinName,
	const FName& OriginalPinName,
	int32 PropertyOwnerIndex)
{
	// Omit trivial cases that runtime lookup can infer
	if (PropertyOwnerIndex == 0 && FinalPinName == OriginalPinName)
	{
		return;
	}

	FlowNode.MapDataPinNameToPropertySource.Add(
		FinalPinName,
		FFlowPinPropertySource(OriginalPinName, PropertyOwnerIndex));
}

void FFlowAutoDataPinsWorkingData::DisambiguateDuplicateOutputDataPin(
	FFlowPinSourceData& PinSourceData,
	TSet<FName>& InOutUsedNames,
	uint32 LogicalDuplicateIndex)
{
	const FName BaseName = PinSourceData.FlowPin.PinName;

	uint32 DisambiguationSuffix = LogicalDuplicateIndex;
	while (true)
	{
		const FName Candidate = FName(FString::Printf(TEXT("%s_%u"), *BaseName.ToString(), DisambiguationSuffix));
		if (!InOutUsedNames.Contains(Candidate))
		{
			PinSourceData.FlowPin.PinName = Candidate;
			InOutUsedNames.Add(Candidate);

			break;
		}

		++DisambiguationSuffix;

		if (!ensure(DisambiguationSuffix < 1000000u))
		{
			UE_LOG(LogFlow, Error, TEXT("Pin name disambiguation failed for %s"), *BaseName.ToString());
			break;
		}
	}

	// Apply friendly name with logical (1-based) duplicate index
	const FString FriendlyStr = FString::Printf(TEXT("%s (%u)"), *PinSourceData.FlowPin.PinFriendlyName.ToString(), LogicalDuplicateIndex);
	PinSourceData.FlowPin.PinFriendlyName = FText::FromString(FriendlyStr);

	// Enhance tooltip with source information
	FString& Tooltip = PinSourceData.FlowPin.PinToolTip;
	if (!PinSourceData.PropertyOwnerObjectName.IsNone())
	{
		if (!Tooltip.IsEmpty())
		{
			Tooltip += TEXT("\n");
		}

		Tooltip += FString::Printf(TEXT("Output of %s"), *PinSourceData.PropertyOwnerObjectName.ToString());
	}

	// Update blueprint-facing property name
	if (PinSourceData.DataPinValue)
	{
		PinSourceData.DataPinValue->PropertyPinName = PinSourceData.FlowPin.PinName;
	}
}

#endif
