// Copyright https://github.com/MothCocoon/FlowGraph/graphs/contributors

#include "Types/FlowAutoDataPinsWorkingData.h"

#include "FlowLogChannels.h"
#include "Nodes/FlowNode.h"
#include "Types/FlowDataPinValue.h"
#include "Types/FlowNamedDataPinProperty.h"
#include "Types/FlowStructUtils.h"

#if WITH_EDITOR

void FFlowAutoDataPinsWorkingData::Build(UFlowNode& FlowNode, FBuildResult& OutBuildResult) const
{
	OutBuildResult.Reset();

	// Disambiguation should not mutate the provider-collected arrays; work on locals.
	TArray<FFlowPinSourceData> InputPinsLocal = AutoInputDataPinsNext;
	TArray<FFlowPinSourceData> OutputPinsLocal = AutoOutputDataPinsNext;

	// Build mapping and apply disambiguation to locals.
	AddInputDataPinsToMapAndDisambiguate(InputPinsLocal, OutBuildResult.MapDataPinNameToPropertySource, OutBuildResult.DeferredValuePatches);
	AddOutputDataPinsToMapAndDisambiguate(OutputPinsLocal, OutBuildResult.MapDataPinNameToPropertySource, OutBuildResult.DeferredValuePatches);

	BuildNextFlowPinArray(InputPinsLocal, OutBuildResult.AutoInputPins);
	BuildNextFlowPinArray(OutputPinsLocal, OutBuildResult.AutoOutputPins);
}

bool FFlowAutoDataPinsWorkingData::CheckIfProposedPinsMatchPreviousPins(const TArray<FFlowPin>& PrevPins, const TArray<FFlowPin>& ProposedPins)
{
	if (PrevPins.Num() != ProposedPins.Num())
	{
		return false;
	}

	for (int32 Index = 0; Index < PrevPins.Num(); ++Index)
	{
		if (!PrevPins[Index].DeepIsEqual(ProposedPins[Index]))
		{
			return false;
		}
	}

	return true;
}

bool FFlowAutoDataPinsWorkingData::ArePropertySourcesEqual(const FFlowPinPropertySource& A, const FFlowPinPropertySource& B)
{
	return A.PropertyName == B.PropertyName && A.ValueOwnerIndex == B.ValueOwnerIndex;
}

bool FFlowAutoDataPinsWorkingData::CheckIfProposedMapMatchesPreviousMap(
	const TMap<FName, FFlowPinPropertySource>& PrevMap,
	const TMap<FName, FFlowPinPropertySource>& ProposedMap)
{
	if (PrevMap.Num() != ProposedMap.Num())
	{
		return false;
	}

	for (const TPair<FName, FFlowPinPropertySource>& KVP : PrevMap)
	{
		const FFlowPinPropertySource* Other = ProposedMap.Find(KVP.Key);
		if (!Other || !ArePropertySourcesEqual(KVP.Value, *Other))
		{
			return false;
		}
	}

	return true;
}

void FFlowAutoDataPinsWorkingData::BuildNextFlowPinArray(const TArray<FFlowPinSourceData>& PinSourceDatas, TArray<FFlowPin>& OutFlowPins)
{
	OutFlowPins.Reset();

	for (const FFlowPinSourceData& PinSourceData : PinSourceDatas)
	{
		OutFlowPins.Add(PinSourceData.FlowPin);
	}
}

void FFlowAutoDataPinsWorkingData::AddFlowDataPinsForClassProperties(FFlowDataPinValueOwner& ValueOwner)
{
	const UObject* ValueOwnerAsObject = ValueOwner.GetValueOwnerAsObject();
	const UClass* Class = ValueOwnerAsObject->GetClass();

	for (TFieldIterator<FProperty> PropertyIt(Class); PropertyIt; ++PropertyIt)
	{
		AddFlowDataPinForProperty(*PropertyIt, ValueOwner);
	}
}

void FFlowAutoDataPinsWorkingData::AddFlowDataPinForProperty(FProperty* Property, FFlowDataPinValueOwner& ValueOwner)
{
	bool bIsInputPin = false;

	const FString* AutoPinType = nullptr;
	const FString* SourceForOutputFlowPinName = nullptr;
	const FString* DefaultForInputFlowPinName = nullptr;

	void* ValueOwnerAsObject = ValueOwner.GetValueOwnerAsObject();

	FStructProperty* StructProperty = CastField<FStructProperty>(Property);
	const FFlowDataPinValue* DataPinValue = nullptr;
	if (StructProperty && StructProperty->Struct)
	{
		const UScriptStruct* ScriptStruct = StructProperty->Struct;

		if (StructProperty->Struct->IsChildOf<FFlowNamedDataPinProperty>())
		{
			// Special-case handling for FFlowNamedDataPinProperty
			// (it has its own function to create the pin)
			FFlowNamedDataPinProperty* NamedPinProperty = FlowStructUtils::CastStructValue<FFlowNamedDataPinProperty>(StructProperty, ValueOwnerAsObject);
			NamedPinProperty->AutoGenerateDataPinForProperty(ValueOwner, *this);

			return;
		}

		AutoPinType = ScriptStruct->FindMetaData(FFlowPin::MetadataKey_FlowPinType);
		SourceForOutputFlowPinName = ScriptStruct->FindMetaData(FFlowPin::MetadataKey_SourceForOutputFlowPin);
		DefaultForInputFlowPinName = ScriptStruct->FindMetaData(FFlowPin::MetadataKey_DefaultForInputFlowPin);

		// For blueprint use, we allow the Value structs to set input pins via editor-only data
		DataPinValue = FlowStructUtils::CastStructValue<FFlowDataPinValue>(StructProperty, ValueOwnerAsObject);
		if (DataPinValue)
		{
			bIsInputPin = DataPinValue->IsInputPin();
		}
	}

	if (!AutoPinType)
	{
		AutoPinType = Property->FindMetaData(FFlowPin::MetadataKey_FlowPinType);

		if (!AutoPinType)
		{
			return;
		}
	}

	const FFlowPinType* FlowPinType = FFlowPinType::LookupPinType(FFlowPinTypeName(*AutoPinType));
	if (!FlowPinType)
	{
		UE_LOG(LogFlow, Error, TEXT("Unknown pin type %s for property %s"), **AutoPinType, *Property->GetName());

		return;
	}

	if (!SourceForOutputFlowPinName)
	{
		SourceForOutputFlowPinName = Property->FindMetaData(FFlowPin::MetadataKey_SourceForOutputFlowPin);
	}

	if (!DefaultForInputFlowPinName)
	{
		DefaultForInputFlowPinName = Property->FindMetaData(FFlowPin::MetadataKey_DefaultForInputFlowPin);
	}

	if (SourceForOutputFlowPinName && DefaultForInputFlowPinName)
	{
		UE_LOG(LogFlow, Error, TEXT("Error.  A property cannot be both a %s and %s"),
		       *FFlowPin::MetadataKey_SourceForOutputFlowPin.ToString(),
		       *FFlowPin::MetadataKey_DefaultForInputFlowPin.ToString());

		return;
	}

	bIsInputPin = bIsInputPin || DefaultForInputFlowPinName != nullptr;

	// Default assumption is the pin will be an output pin, unless metadata specifies otherwise
	TArray<FFlowPinSourceData>* FlowPinArray = bIsInputPin ? &AutoInputDataPinsNext : &AutoOutputDataPinsNext;

	// Create the new FlowPin
	FFlowPin NewFlowPin = FlowPinType->CreateFlowPinFromProperty(*Property, ValueOwnerAsObject);

	// Potentially override the PinFriendlyName if the metadata specified an alternative
	if (DefaultForInputFlowPinName)
	{
		const FString SpecifyInputPinNameString = *DefaultForInputFlowPinName;
		if (SpecifyInputPinNameString.Len() > 0)
		{
			NewFlowPin.PinFriendlyName = FText::FromString(SpecifyInputPinNameString);
		}
	}
	else if (SourceForOutputFlowPinName)
	{
		const FString SpecifyOutputPinNameString = *SourceForOutputFlowPinName;
		if (SpecifyOutputPinNameString.Len() > 0)
		{
			NewFlowPin.PinFriendlyName = FText::FromString(SpecifyOutputPinNameString);
		}
	}

	FlowPinArray->Add(FFlowPinSourceData(NewFlowPin, ValueOwner, DataPinValue));

	// IMPORTANT: wrapper patching is deferred until commit time to avoid dirtying assets on a no-op regen.
}

void FFlowAutoDataPinsWorkingData::AddPinMappingToMap(
	TMap<FName, FFlowPinPropertySource>& InOutMap,
	const FName& FinalPinName,
	const FName& OriginalPinName,
	const FFlowDataPinValueOwner& ValueOwner)
{
	if (ValueOwner.IsDefaultValueOwner() && FinalPinName == OriginalPinName)
	{
		return;
	}

	InOutMap.Add(FinalPinName, FFlowPinPropertySource(OriginalPinName, ValueOwner.ValueOwnerIndex));
}

void FFlowAutoDataPinsWorkingData::AppendDeferredPatchIfNeeded(
	TArray<FDeferredValuePinNamePatch>& InOutPatches,
	const FFlowPinSourceData& PinSourceData)
{
	if (!PinSourceData.DataPinValue)
	{
		return;
	}

	FDeferredValuePinNamePatch Patch;
	Patch.DataPinValue = PinSourceData.DataPinValue;
	Patch.NewPinName = PinSourceData.FlowPin.PinName;
	InOutPatches.Add(Patch);
}

bool FFlowAutoDataPinsWorkingData::AreFlowPinTypeSignaturesEquivalent(const FFlowPin& A, const FFlowPin& B)
{
	// Type signature equivalence (matches your requirement for "same type"):
	// - ContainerType
	// - PinTypeName
	// - PinSubCategoryObject
	return
		A.ContainerType == B.ContainerType &&
		A.GetPinTypeName() == B.GetPinTypeName() &&
		A.GetPinSubCategoryObject() == B.GetPinSubCategoryObject();
}

void FFlowAutoDataPinsWorkingData::AddInputDataPinsToMapAndDisambiguate(
	TArray<FFlowPinSourceData>& InOutAutoInputPinsNext,
	TMap<FName, FFlowPinPropertySource>& InOutMap,
	TArray<FDeferredValuePinNamePatch>& InOutDeferredPatches)
{
	if (InOutAutoInputPinsNext.IsEmpty())
	{
		return;
	}

	// Pass 1: count each base/original name (array order deterministic)
	TMap<FName, int32> NameCounts;
	for (const FFlowPinSourceData& Pin : InOutAutoInputPinsNext)
	{
		if (!Pin.FlowPin.IsExecPin())
		{
			NameCounts.FindOrAdd(Pin.FlowPin.PinName)++;
		}
	}

	// Determine which base names actually require disambiguation (duplicates + mismatched type signature)
	TSet<FName> NamesRequiringDisambiguation;

	for (const TPair<FName, int32>& KVP : NameCounts)
	{
		const FName BaseName = KVP.Key;
		const int32 Count = KVP.Value;

		if (Count <= 1)
		{
			continue;
		}

		const FFlowPin* FirstTypePin = nullptr;
		bool bMismatchFound = false;

		for (const FFlowPinSourceData& Pin : InOutAutoInputPinsNext)
		{
			if (Pin.FlowPin.IsExecPin() || Pin.FlowPin.PinName != BaseName)
			{
				continue;
			}

			if (!FirstTypePin)
			{
				FirstTypePin = &Pin.FlowPin;
				continue;
			}

			if (!AreFlowPinTypeSignaturesEquivalent(*FirstTypePin, Pin.FlowPin))
			{
				bMismatchFound = true;
				break;
			}
		}

		if (bMismatchFound)
		{
			NamesRequiringDisambiguation.Add(BaseName);
		}
	}

	// Collect names that will remain unchanged (for collision avoidance during renaming)
	TSet<FName> ReservedFinalNames;
	for (const FFlowPinSourceData& Pin : InOutAutoInputPinsNext)
	{
		if (Pin.FlowPin.IsExecPin())
		{
			continue;
		}

		const FName BaseName = Pin.FlowPin.PinName;

		// If this base name requires disambiguation, none of its occurrences are reserved
		if (NamesRequiringDisambiguation.Contains(BaseName))
		{
			continue;
		}

		// Only reserve true uniques (Count==1). Duplicate-but-mergeable can keep their base name,
		// but reserving it doesn't help us because we won't rename those anyway.
		const int32 Count = NameCounts.FindRef(BaseName);
		if (Count == 1)
		{
			ReservedFinalNames.Add(BaseName);
		}
	}

	// Walk in provider order; map unique and mergeable duplicates, disambiguate mismatch-type duplicates
	TSet<FName> UsedNames = ReservedFinalNames;
	TMap<FName, uint32> NextLogicalDuplicateIndexByName;

	for (FFlowPinSourceData& Pin : InOutAutoInputPinsNext)
	{
		if (Pin.FlowPin.IsExecPin())
		{
			continue;
		}

		const FName OriginalName = Pin.FlowPin.PinName;

		if (!NamesRequiringDisambiguation.Contains(OriginalName))
		{
			// No rename required (either unique, or duplicate but mergeable by type signature).
			// Preserve name so FlowNode-level "merge by name" remains.

			if (!Pin.ValueOwner.IsDefaultValueOwner())
			{
				AddPinMappingToMap(InOutMap, Pin.FlowPin.PinName, Pin.FlowPin.PinName, Pin.ValueOwner);
			}

			AppendDeferredPatchIfNeeded(InOutDeferredPatches, Pin);
			continue;
		}

		// Disambiguate this entry deterministically in encounter order
		uint32& NextLogicalIndex = NextLogicalDuplicateIndexByName.FindOrAdd(OriginalName);
		if (NextLogicalIndex == 0)
		{
			NextLogicalIndex = 1;
		}

		const uint32 LogicalDuplicateIndex = NextLogicalIndex;
		++NextLogicalIndex;

		DisambiguateDuplicatePin(Pin, UsedNames, LogicalDuplicateIndex, InOutDeferredPatches);

		// IMPORTANT: for disambiguated pins, ALWAYS add a mapping entry (even for default owner),
		// because runtime fallback inference assumes "PinName == PropertyName on owner 0".
		AddPinMappingToMap(InOutMap, Pin.FlowPin.PinName, OriginalName, Pin.ValueOwner);
	}
}

void FFlowAutoDataPinsWorkingData::AddOutputDataPinsToMapAndDisambiguate(
	TArray<FFlowPinSourceData>& InOutAutoOutputPinsNext,
	TMap<FName, FFlowPinPropertySource>& InOutMap,
	TArray<FDeferredValuePinNamePatch>& InOutDeferredPatches)
{
	if (InOutAutoOutputPinsNext.IsEmpty())
	{
		return;
	}

	// Pass 1: count each base/original name (array order deterministic)
	TMap<FName, int32> NameCounts;
	for (const FFlowPinSourceData& Pin : InOutAutoOutputPinsNext)
	{
		if (!Pin.FlowPin.IsExecPin())
		{
			NameCounts.FindOrAdd(Pin.FlowPin.PinName)++;
		}
	}

	// Collect names that will remain unchanged (for collision avoidance during renaming)
	TSet<FName> ReservedFinalNames;
	for (const FFlowPinSourceData& Pin : InOutAutoOutputPinsNext)
	{
		if (Pin.FlowPin.IsExecPin())
		{
			continue;
		}

		const int32 Count = NameCounts.FindRef(Pin.FlowPin.PinName);
		if (Count == 1)
		{
			ReservedFinalNames.Add(Pin.FlowPin.PinName);
		}
	}

	// Pass 2: walk in array order; assign mapping for unique pins, disambiguate duplicates deterministically in-place
	TSet<FName> UsedNames = ReservedFinalNames;
	TMap<FName, uint32> NextLogicalDuplicateIndexByName;

	for (FFlowPinSourceData& Pin : InOutAutoOutputPinsNext)
	{
		if (Pin.FlowPin.IsExecPin())
		{
			continue;
		}

		const FName OriginalName = Pin.FlowPin.PinName;
		const int32 Count = NameCounts.FindRef(OriginalName);

		if (Count <= 1)
		{
			if (!Pin.ValueOwner.IsDefaultValueOwner())
			{
				AddPinMappingToMap(
					InOutMap,
					Pin.FlowPin.PinName,
					Pin.FlowPin.PinName,
					Pin.ValueOwner);
			}

			AppendDeferredPatchIfNeeded(InOutDeferredPatches, Pin);
			continue;
		}

		uint32& NextLogicalIndex = NextLogicalDuplicateIndexByName.FindOrAdd(OriginalName);
		if (NextLogicalIndex == 0)
		{
			NextLogicalIndex = 1;
		}

		const uint32 LogicalDuplicateIndex = NextLogicalIndex;
		++NextLogicalIndex;

		DisambiguateDuplicatePin(Pin, UsedNames, LogicalDuplicateIndex, InOutDeferredPatches);

		AddPinMappingToMap(
			InOutMap,
			Pin.FlowPin.PinName,
			OriginalName,
			Pin.ValueOwner);
	}
}

void FFlowAutoDataPinsWorkingData::DisambiguateDuplicatePin(
	FFlowPinSourceData& PinSourceData,
	TSet<FName>& InOutUsedNames,
	uint32 LogicalDuplicateIndex,
	TArray<FDeferredValuePinNamePatch>& InOutDeferredPatches)
{
	const FName BaseName = PinSourceData.FlowPin.PinName;

	uint32 DisambiguationSuffix = LogicalDuplicateIndex;
	while (true)
	{
		const FName Candidate = FName(FString::Printf(TEXT("%s_%u"), *BaseName.ToString(), DisambiguationSuffix));
		if (!InOutUsedNames.Contains(Candidate))
		{
			PinSourceData.FlowPin.PinName = Candidate;
			InOutUsedNames.Add(Candidate);

			break;
		}

		++DisambiguationSuffix;

		if (!ensure(DisambiguationSuffix < 1000000u))
		{
			UE_LOG(LogFlow, Error, TEXT("Pin name disambiguation failed for %s"), *BaseName.ToString());
			break;
		}
	}

	ApplyDuplicatePresentation(PinSourceData, LogicalDuplicateIndex);
	AppendPinSourceToTooltip(PinSourceData);

	AppendDeferredPatchIfNeeded(InOutDeferredPatches, PinSourceData);
}

void FFlowAutoDataPinsWorkingData::ApplyDuplicatePresentation(
	FFlowPinSourceData& PinSourceData,
	uint32 LogicalDuplicateIndex)
{
	const FString FriendlyStr = FString::Printf(TEXT("%s (%u)"), *PinSourceData.FlowPin.PinFriendlyName.ToString(), LogicalDuplicateIndex);
	PinSourceData.FlowPin.PinFriendlyName = FText::FromString(FriendlyStr);
}

void FFlowAutoDataPinsWorkingData::AppendPinSourceToTooltip(FFlowPinSourceData& PinSourceData)
{
	FString& Tooltip = PinSourceData.FlowPin.PinToolTip;

	const FName ValueOwnerName = PinSourceData.ValueOwner.GetValueOwnerName();
	if (!ValueOwnerName.IsNone())
	{
		if (!Tooltip.IsEmpty())
		{
			Tooltip += TEXT("\n");
		}

		Tooltip += FString::Printf(TEXT("Output of %s"), *ValueOwnerName.ToString());
	}
}

#endif

UObject* FFlowDataPinValueOwner::GetValueOwnerAsObject()
{
	return CastChecked<UObject>(OwnerInterface, ECastCheckedType::NullAllowed);
}

const UObject* FFlowDataPinValueOwner::GetValueOwnerAsObject() const
{
	return CastChecked<UObject>(OwnerInterface, ECastCheckedType::NullAllowed);
}

void FFlowDataPinValueOwnerCollection::AddValueOwner(IFlowDataPinValueOwnerInterface& ValueOwnerInterface)
{
	const int32 ValueOwnerIndex = ValueOwners.Num();
	ValueOwners.Add(FFlowDataPinValueOwner(ValueOwnerInterface, ValueOwnerIndex));
}