// Copyright https://github.com/MothCocoon/FlowGraph/graphs/contributors

#pragma once

#include "Misc/EnumClassFlags.h"
#include "UObject/NoExportTypes.h"
#include "FlowCatalogQuery.generated.h"

class UFlowNode;
class UFlowNodeBase;
class UFlowNodeAddOn;
struct FFlowPin;

/**
 * How a Flow node or addon class came to exist, which decides where its authored documentation can
 * physically live: a Blueprint stores it as a saved class default, a native class returns a
 * compiled-in constant from a C++ override, and a script class declares it in its own source.
 *
 * An enum rather than a string so the value cannot be misspelled, and so the generated MCP schema
 * enumerates the legal values for a caller instead of accepting any string and silently matching
 * nothing.
 */
UENUM(BlueprintType)
enum class EFlowClassOrigin : uint8
{
	/** Filter-only: match every origin. Never reported on a row. */
	Any = 0,

	/** Declared in C++ and compiled in. */
	Native,

	/** Generated from a Blueprint asset, so its defaults are serialized and savable. */
	Blueprint,

	/** Generated by the AngelScript integration; its doc lives in an EDITOR block in the .as source. */
	AngelScript,

	/**
	 * Reflected as generated by something other than a Blueprint, but not a scripting integration this
	 * module recognises. Reported rather than guessed at - a class landing here is worth investigating,
	 * not silently filing under one of the others.
	 */
	Unknown,
};

/**
 * The stable, lower-case wire name for an origin, for JSON and any other machine-read output.
 *
 * Deliberately NOT UEnum::GetDisplayValueText(): that returns localizable FText, so a machine-read
 * payload built from it would change shape under a non-English editor. Display text is for UI.
 */
FLOWGRAPHCOURIER_API FString LexToString(EFlowClassOrigin Origin);

/** Parses a wire name back to an origin. Returns false for anything unrecognised - never guesses. */
FLOWGRAPHCOURIER_API bool LexTryParseString(EFlowClassOrigin& OutOrigin, const FStringView Text);

/**
 * Which parts of a catalog row the caller wants, each independently gated.
 *
 * A caller can request a bare name list or combine only the sections it needs.
 */
enum class EFlowCatalogSection : uint32
{
	None = 0,

	/** Category/tag/article histograms with counts and no rows at all - the cheapest cold-start call. */
	Shape = 1 << 0,

	/** The class identifier. Implied by every other row-bearing section. */
	Names = 1 << 1,

	/** Reflected description plus the hand-authored description/guidance/tags and hasDoc. */
	Doc = 1 << 2,

	/** Properties declared on the queried class, plus a per-declaring-class count of inherited ones. */
	Properties = 1 << 3,

	/** Declared input/output pins, read from the CDO. */
	Pins = 1 << 4,

	/** Knowledge-base article slugs the class is a member of. */
	Articles = 1 << 5,

	/** Shipped-usage counts and example assets, from the usage index. */
	Usage = 1 << 6,

	/** How the class was authored - see EFlowClassOrigin. */
	Origin = 1 << 7,

	/** deprecated + replacedBy. */
	Deprecation = 1 << 8,
};
ENUM_CLASS_FLAGS(EFlowCatalogSection);

/** One row of the properties table, gathered across the class's full ancestor chain. */
struct FFlowCatalogPropertyRow
{
	FString Name;
	FString Type;
	FString PinBinding;
	FString Description;

	/** The class that actually declares this property - the queried class itself, or an ancestor. */
	FString DeclaringClass;

	/** Terse stringified current default (bare enum name, not fully scoped; "N elements" for arrays). Empty for opaque struct types. */
	FString Value;
};

/** One row of a class's input/output pin table. */
struct FFlowCatalogPinRow
{
	FString Name;
	FString Type;
	FString Description;

	/**
	 * True for a pin that no CDO declares and that was instead seen on real instances in shipped
	 * content - typically a pin contributed by an attached addon. Not guaranteed to be present.
	 */
	bool bObservedOnly = false;
};

/** The hand-authored documentation layer for one class. */
struct FFlowCatalogDocRow
{
	FString Guidance;
	TArray<FString> Tags;

	/** An undocumented class (empty Guidance and Tags) is normal, not an error. */
	bool IsEmpty() const { return Guidance.IsEmpty() && Tags.IsEmpty(); }
};

/** One resolved node or addon class row. Which fields are populated depends on the requested sections. */
struct FFlowCatalogClassRow
{
	/**
	 * The canonical identifier to emit: the class's bare stem (family prefix and trailing "_C"
	 * stripped), or the full short name when a stem collides with another row in the same response.
	 */
	FString Stem;
	FString ClassName;

	/** The only authoritative identifier. Always populated - never make a caller rebuild it from a stem. */
	FString ClassPath;
	bool bIsAddon = false;
	FString Category;
	FString Description;

	/** Derived from the class, never supplied by a caller. */
	EFlowClassOrigin Origin = EFlowClassOrigin::Unknown;
	bool bDeprecated = false;
	FString ReplacedBy;
	FFlowCatalogDocRow Doc;
	TArray<FString> Articles;
	TArray<FFlowCatalogPropertyRow> Properties;
	TArray<FFlowCatalogPinRow> InputPins;
	TArray<FFlowCatalogPinRow> OutputPins;

	/** INDEX_NONE when the usage section was not requested. */
	int32 UsageCount = INDEX_NONE;
	int32 UsageAssetCount = INDEX_NONE;
};

/** One facet value -> match-count row, computed over the current filter scope. */
struct FFlowCatalogFacetRow
{
	FString Value;
	int32 Count = 0;
};

/** A stem that more than one requested class could have meant. Never resolved on the caller's behalf. */
struct FFlowCatalogAmbiguousNameRow
{
	FString Stem;
	TArray<FString> Candidates;
};

/** One FlowAsset subclass row at the ListAssetTypes level - counts only, never the member name arrays. */
struct FFlowCatalogAssetTypeRow
{
	FString ClassName;
	FString ClassPath;
	FString Description;
	FString Keywords;
	int32 AllowedNodeCount = 0;
	int32 AllowedAddonCount = 0;
};

/** Node/addon scope filter for FindFlowNodeTypes / QueryCatalog. */
UENUM(BlueprintType)
enum class EFlowCatalogKind : uint8
{
	Node,
	Addon,
	Any,
};

/** Parameters for UFlowCatalogQuery::QueryCatalog - the single query core behind every catalog consumer. */
struct FFlowCatalogQueryParams
{
	/** Restrict to classes legal on this FlowAsset subclass (short name or full path); empty = whole project. */
	FString AssetClassName;
	/**
	 * Stems, full short names, or full class paths. When non-empty, this is the ONLY filter applied -
	 * all others below are ignored - and deprecated classes always resolve regardless of
	 * bIncludeDeprecated, because reading a legacy graph is precisely when they must be findable.
	 */
	TArray<FString> ClassNames;
	EFlowCatalogKind Kind = EFlowCatalogKind::Any;

	/** Case-insensitive substring match over class name + reflected description. */
	FString Query;

	/** Exact, lower-cased. A class matches if it carries ANY listed keyword or authored tag. */
	TArray<FString> Keywords;

	/** Exact. A class matches if it is in ANY listed category. */
	TArray<FString> Categories;

	/** Exact, lower-cased article slugs ("pattern:<slug>"). A class matches if it carries ANY listed slug. */
	TArray<FString> Articles;

	/** Existing pin-type filter semantics - a class matches if it declares a pin of any listed type. */
	TArray<FString> PinTypes;

	/**
	 * Restrict to one origin. Defaults to Any.
	 *
	 * Documentation work batches by origin, because where a class's doc has to be written differs
	 * entirely per origin - a saved CDO default, a C++ override, or an .as EDITOR block.
	 */
	EFlowClassOrigin Origin = EFlowClassOrigin::Any;

	/** Which sections to populate. Defaults to Shape, the cheapest useful answer. */
	EFlowCatalogSection Sections = EFlowCatalogSection::Shape;

	/** True to report only the reflected Description rather than the full authored doc - the "brief" preset. */
	bool bDescriptionOnly = false;

	/** Deprecated classes are gathered either way, but filtered out of filtered-query results unless this is set. */
	bool bIncludeDeprecated = false;

	/** 0 = unlimited. */
	int32 Limit = 0;
	int32 Offset = 0;
};

/**
 * Category/tag/article histograms plus scope counts - the Shape section's payload.
 *
 * Each facet list is ranked by count and capped at MaxShapeFacets. The matching Distinct*Count and
 * Other*Count fields describe the tail that was cut, so a caller can always tell a complete list from
 * a truncated one instead of mistaking the cap for the whole vocabulary.
 */
struct FFlowCatalogShape
{
	TArray<FFlowCatalogFacetRow> Categories;
	TArray<FFlowCatalogFacetRow> Keywords;
	TArray<FFlowCatalogFacetRow> Tags;
	TArray<FFlowCatalogFacetRow> Articles;
	int32 NodeCount = 0;
	int32 AddonCount = 0;
	int32 DocumentedCount = 0;
	int32 DeprecatedCount = 0;
	int32 DistinctCategoryCount = 0;
	int32 DistinctKeywordCount = 0;
	int32 DistinctTagCount = 0;
	int32 DistinctArticleCount = 0;

	/** Total occurrences falling outside the capped facet list, per facet kind. */
	int32 OtherCategoryCount = 0;
	int32 OtherKeywordCount = 0;
	int32 OtherTagCount = 0;
	int32 OtherArticleCount = 0;
};

/** Result for UFlowCatalogQuery::QueryCatalog. */
struct FFlowCatalogQueryResult
{
	TArray<FFlowCatalogClassRow> Nodes;
	TArray<FFlowCatalogClassRow> Addons;

	/** Pre-paging match counts (i.e. before Limit/Offset are applied). */
	int32 TotalNodeCount = 0;
	int32 TotalAddonCount = 0;
	bool bTruncated = false;

	/** Echo of the sections actually applied, lower-cased and comma-joined. */
	FString EffectiveSections;
	FFlowCatalogShape Shape;

	/** Names in ClassNames[] that resolved to nothing. */
	TArray<FString> UnresolvedClassNames;

	/** Stems in ClassNames[] that matched more than one class. Deliberately left unresolved. */
	TArray<FFlowCatalogAmbiguousNameRow> AmbiguousClassNames;

	/** Non-empty => the query was rejected outright. Callers must check this before trusting Nodes/Addons. */
	FString ErrorMessage;
};

/**
 * Query core over every FlowNode / FlowNodeAddOn / FlowAsset class in the project - native,
 * script-generated and Blueprint-generated alike.
 *
 * Serves reflected structure (category, own/inherited properties, declared pins, origin,
 * deprecation) alongside the hand-authored documentation layer each class carries, so a caller gets
 * both what a class *is* and what it is *for* from one place. Backs the Flow MCP discovery ops as
 * well as the file-only bulk export; every consumer routes through QueryCatalog/ListAssetTypes so
 * the live ops and the bulk feed can never disagree.
 */
UCLASS(BlueprintType)
class FLOWGRAPHCOURIER_API UFlowCatalogQuery : public UObject
{
	GENERATED_BODY()

public:
	/**
	 * The single query core. Filters (AssetClassName/Kind/Query/Keywords/Categories/Articles/
	 * PinTypes) are ANDed together; ClassNames is exclusive - when non-empty, it is the only filter
	 * applied. Sections controls which parts of each row are populated; requesting only Shape
	 * returns histograms and no rows at all.
	 */
	static void QueryCatalog(const FFlowCatalogQueryParams& Params, FFlowCatalogQueryResult& OutResult);

	/** Lists every concrete FlowAsset subclass with counts only - the cold-start entry point for Flow discovery. */
	static void ListAssetTypes(TArray<FFlowCatalogAssetTypeRow>& OutAssetTypes);

	/**
	 * JSON-string wrapper over QueryCatalog for Blueprint/Python callers
	 * (unreal.FlowCatalogQuery.query_flow_catalog_as_json). Kind accepts "node"|"addon"|"any";
	 * Sections accepts a comma-separated list of section names and/or the presets "shape", "brief"
	 * and "full".
	 * @return A JSON object string with the same shape as FFlowCatalogQueryResult.
	 */
	UFUNCTION(BlueprintCallable, Category = "FlowGraph|Catalog")
	static FString QueryFlowCatalogAsJson(
		const FString& AssetClassName,
		const TArray<FString>& ClassNames,
		const FString& Kind,
		const FString& Query,
		const TArray<FString>& Keywords,
		const TArray<FString>& Categories,
		const TArray<FString>& Articles,
		const TArray<FString>& PinTypes,
		EFlowClassOrigin Origin,
		const FString& Sections,
		bool bIncludeDeprecated,
		int32 Limit,
		int32 Offset);

	/**
	 * Writes the complete catalog - optionally scoped to one FlowAsset subclass's allowed set - to a
	 * UTF-8 JSON file on disk, deprecated classes included. File-only by design: there is no
	 * string-returning bulk variant, so no caller can pull the whole catalog into context by
	 * accident. The usage section is deliberately excluded, since building the usage index over every
	 * FlowAsset in the project would dominate the export's cost.
	 * @param OutputFilePath Path to write the JSON file to.
	 * @param AssetClassName Optional filter - if non-empty, only classes allowed on this FlowAsset subclass are included.
	 * @return True if the export succeeded, false otherwise.
	 */
	UFUNCTION(BlueprintCallable, Category = "FlowGraph|Catalog")
	static bool ExportFlowCatalogToFile(const FString& OutputFilePath, const FString& AssetClassName);

public:
	/**
	 * Gathers every concrete node class, deprecated ones included. Deprecation is a reported fact and
	 * a default result filter, never a gather-time exclusion - hiding a deprecated class here would
	 * make the legacy graph that still references it undocumentable.
	 */
	static void GatherAllNodeClasses(TArray<UClass*>& OutNodeClasses);

	static void GatherAllAddOnClasses(TArray<UClass*>& OutAddOnClasses);
	static void GatherAllFlowAssetClasses(TArray<UClass*>& OutAssetClasses);

	/**
	 * Finds a node or addon class by stem, short name (UClass::GetName()), or full class path.
	 * Returns nullptr when nothing matches or when a stem is ambiguous.
	 */
	static UClass* FindFlowNodeOrAddOnClassByName(const FString& ClassName);

	/** The class's reflected tooltip, in full. Truncation is the caller's business, not the catalog's. */
	static FString GetNodeDescription(const UClass* NodeOrAddOnClass);

	/** The class's authored category. Reads through UFlowNodeBase, so addons report a category too. */
	static FString GetNodeCategory(const UClass* NodeOrAddOnClass);

	/** How the class was authored. Derived from reflection; there is no caller-supplied override. */
	static EFlowClassOrigin GetClassOrigin(const UClass* NodeOrAddOnClass);

	/** True when the class's CDO sets bNodeDeprecated - the one deprecation mechanism, project-wide. */
	static bool IsClassDeprecated(const UClass* NodeOrAddOnClass);

	/** The short name of the class's declared successor, or empty when none is set. */
	static FString GetReplacedByClassName(const UClass* NodeOrAddOnClass);

	/** The class's hand-authored documentation, read through UFlowNodeBase::GetAgentDoc(). */
	static void GatherAgentDoc(const UClass* NodeOrAddOnClass, FFlowCatalogDocRow& OutDoc, TArray<FString>& OutArticles);

	/**
	 * The bare stem for a class name: trailing "_C" and the leading family prefix removed. Purely a
	 * presentation affordance - ClassPath remains the authoritative identifier.
	 */
	static FString MakeClassStem(const FString& ClassName);

	static FString GetPropertyTypeName(const FProperty* Property);
	static FString GetPropertyTooltip(const FProperty* Property);
	static FString GetPropertyPinBinding(const FProperty* Property);

	/** Terse stringified current value read from ContainerPtr - see FFlowCatalogPropertyRow::Value for the format rules. */
	static FString GetPropertyValueString(const FProperty* Property, const void* ContainerPtr);

	static FString GetPinTypeName(const FFlowPin& Pin);

	static bool CanNodeAddUserInputPins(const UClass* NodeClass);
	static bool CanNodeAddUserOutputPins(const UClass* NodeClass);

	/**
	 * Builds a map of keyword → sorted list of display names for every node and addon that carries that keyword.
	 * Keywords are split on whitespace and comma, trimmed, and lower-cased for deduplication.
	 * @param NodeClasses     The node classes to inspect (already gathered and filtered).
	 * @param AddOnClasses    The addon classes to inspect (already gathered and filtered).
	 * @param OutKeywordMap   Output map: keyword (lower-case) → sorted display-name list.
	 */
	static void GatherAllKeywords(
		const TArray<UClass*>& NodeClasses,
		const TArray<UClass*>& AddOnClasses,
		TMap<FString, TArray<FString>>& OutKeywordMap);

	/**
	 * True if PinTypeFilter is empty (no filter), or if NodeOrAddOnClass declares at least one
	 * input/output pin whose Type is in PinTypeFilter. Only considers CDO-declared pins.
	 */
	static bool ClassHasPinOfAnyType(const UClass* NodeOrAddOnClass, const TArray<FString>& PinTypeFilter);

	/**
	 * Reads a class's declared pins from its CDO via UFlowNodeBase::GetCatalogPins, so a class that
	 * generates its pins procedurally reports them instead of appearing pinless. Addons report the
	 * pins they contribute to their parent. Pins contributed by *attached* addons cannot come from a
	 * CDO and are therefore absent; the usage index covers that narrow slice.
	 */
	static void GatherPins(const UClass* NodeOrAddOnClass, TArray<FFlowCatalogPinRow>& OutInputPins, TArray<FFlowCatalogPinRow>& OutOutputPins);

	/**
	 * Gathers every configurable or pin-bound property across the class's full ancestor chain, each
	 * row tagged with its DeclaringClass so a caller can distinguish the queried class's own knobs
	 * from ones it inherits without losing detail on the latter.
	 */
	static void GatherProperties(const UClass* NodeOrAddOnClass, TArray<FFlowCatalogPropertyRow>& OutRows);

	/**
	 * Parses a comma-separated section list into a section mask. Accepts individual section names
	 * and the presets "shape" (default), "brief" and "full". Returns false and sets OutError on an
	 * unknown value - a typo must not silently degrade the response.
	 */
	static bool ParseSections(const FString& SectionsString, EFlowCatalogSection& OutSections, bool& bOutDescriptionOnly, FString& OutError);

	/** Renders a section mask back to its comma-separated lower-case name list. */
	static FString SectionsToString(EFlowCatalogSection Sections);

	/** Parses a "node"|"addon"|"any" string (case-insensitive; anything else, including empty, defaults to Any). */
	static EFlowCatalogKind ParseKind(const FString& KindString);

private:
	/* Returns Keywords metadata from the UCLASS, or empty string. */
	static FString GetNodeKeywords(const UClass* NodeClass);

	/** Projects one resolved class into a row carrying exactly the requested sections. */
	static FFlowCatalogClassRow BuildRow(const UClass* Class, bool bIsAddon, const FFlowCatalogQueryParams& Params);

	/**
	 * Assigns each row's Stem. A stem unique within the response is emitted bare; when two rows of
	 * the same kind share one, the precedence ladder decides which keeps it and the loser falls back
	 * to its full class name. Lossless, deterministic, and free for the ~98% of classes that never
	 * collide.
	 */
	static void ResolveStems(TArray<FFlowCatalogClassRow>& Rows);
};
