// Copyright https://github.com/MothCocoon/FlowGraph/graphs/contributors

#pragma once

#include "UObject/Object.h"
#include "FlowGraphSubgraphQuery.generated.h"

class UFlowAsset;
class UFlowNode;

/**
 * One node returned by FFlowGraphSubgraphQuery::FindNodes - a lightweight summary (GUID, title,
 * class, entry-point flag), not a full exported node block. Callers that need the full node body
 * should follow up with FFlowGraphSubgraphQuery::ExportSubgraph or export_flow_asset.
 */
USTRUCT(BlueprintType)
struct FLOWGRAPHCOURIER_API FFlowSubgraphNodeSummary
{
	GENERATED_BODY()

	UPROPERTY()
	FGuid NodeGuid;

	// Editor node title (UFlowGraphNode::GetNodeTitle) when an editor graph exists; falls back to
	// the node class's short name (WITH_EDITOR unavailable, or the node has no UEdGraphNode yet).
	UPROPERTY()
	FString Title;

	// Full class path, same form as a mutation document's "Type:" line.
	UPROPERTY()
	FString ClassPath;

	// True iff no other node in the asset has any connection (exec or data) targeting this node.
	UPROPERTY()
	bool bIsEntryPoint = false;
};

/**
 * Targeted reads over a UFlowAsset. FindNodes locates instances by title, class, or entry-point
 * status; ExportSubgraph exports the connected region around a node as a Courier document.
 *
 * Reachability (ExportSubgraph) is the full UNDIRECTED connected component containing the start
 * node - both outgoing and incoming edges, both exec and data pins. AddOns are never
 * traversed independently; every AddOn attached to an included node is serialized as part of that
 * node's own block by the reused exporter (UFlowGraphExporter::ExportFlowGraphSubsetToString).
 *
 * Plain static-method class, not a UObject: it has no UFUNCTIONs and is never instantiated.
 */
class FLOWGRAPHCOURIER_API FFlowGraphSubgraphQuery
{
public:
	/**
	 * Filters Asset's live nodes by title substring (case-insensitive; empty = no filter), class
	 * (short or full name, resolved via UFlowGraphImporter::ResolveNodeClassForQuery; empty = no
	 * filter), and/or entry-point-only (no other node has any connection targeting it).
	 * Returns lightweight summaries, not full node bodies - see FFlowSubgraphNodeSummary.
	 * Returns false if Asset is null or ClassFilter names nothing resolvable (OutErrorMessage set);
	 * an empty result set for a resolvable but non-matching filter is not an error.
	 *
	 * ClassFilter uses the query resolver, not the fail-closed ResolveNodeClass, so that a class
	 * generated by a non-Flow Blueprint stays findable. Being read-only, this is the tool an author
	 * uses to locate such nodes for repair; rejecting them here would report a graph as broken while
	 * hiding which nodes are at fault.
	 */
	static bool FindNodes(
		const UFlowAsset* Asset,
		const FString& TitleFilter,
		const FString& ClassFilter,
		bool bEntryPointsOnly,
		TArray<FFlowSubgraphNodeSummary>& OutResults,
		FString& OutErrorMessage);

	/**
	 * Computes the undirected connected component containing StartNodeGuid (both exec and
	 * data edges, both directions) and re-exports exactly that node/connection subset via
	 * UFlowGraphExporter::ExportFlowGraphSubsetToString - same Flow Courier grammar as a
	 * full export, so the result is independently re-importable. Returns false if Asset is null or
	 * StartNodeGuid does not resolve to a node on Asset (OutErrorMessage set in both cases).
	 */
	static bool ExportSubgraph(
		UFlowAsset* Asset,
		const FGuid& StartNodeGuid,
		FString& OutExportText,
		int32& OutNodeCount,
		FString& OutErrorMessage);

private:
	// Builds every directed edge in Asset (exec: owner -> target; data: source -> owner, matching
	// UFlowGraphExporter::ExportConnections' storage-direction handling) as an undirected adjacency
	// list, then BFS from StartNodeGuid. OutComponent always contains StartNodeGuid itself (even
	// with zero edges) when StartNodeGuid is a real node on Asset.
	static void ComputeConnectedComponent(const UFlowAsset* Asset, const FGuid& StartNodeGuid, TSet<FGuid>& OutComponent);

	// Set of every node GUID that is the target of at least one connection (exec or data) from any
	// other node in Asset. Used by FindNodes' bEntryPointsOnly filter.
	static void ComputeIncomingConnectionTargets(const UFlowAsset* Asset, TSet<FGuid>& OutTargets);

	// Resolves a node's display title for FFlowSubgraphNodeSummary::Title (WITH_EDITOR: the live
	// UFlowGraphNode's title; otherwise the node class's short name).
	static FString ResolveNodeTitle(const UFlowNode* Node);
};
