// Copyright https://github.com/MothCocoon/FlowGraph/graphs/contributors

#include "FlowGraphSubgraphQuery.h"
#include "FlowAsset.h"
#include "FlowGraphExporter.h"
#include "FlowGraphImporter.h"
#include "Nodes/FlowNode.h"
#include "Nodes/FlowPin.h"
#include "EdGraph/EdGraphNode.h"

FString FFlowGraphSubgraphQuery::ResolveNodeTitle(const UFlowNode* Node)
{
	if (!Node)
	{
		return TEXT("");
	}

#if WITH_EDITOR
	if (const UEdGraphNode* EdGraphNode = Node->GetGraphNode())
	{
		return EdGraphNode->GetNodeTitle(ENodeTitleType::ListView).ToString();
	}
#endif

	return Node->GetClass()->GetName();
}

void FFlowGraphSubgraphQuery::ComputeIncomingConnectionTargets(const UFlowAsset* Asset, TSet<FGuid>& OutTargets)
{
	OutTargets.Reset();
	if (!Asset)
	{
		return;
	}

	// Mirrors UFlowGraphExporter::ExportConnections' storage-direction handling: exec connections
	// are stored on the source node keyed by its output pin (the value is the target); data
	// connections are stored on the receiving node keyed by its own input pin (the value is the
	// source). Either way, "the other endpoint" recorded in a valid FConnectedPin is the target of
	// an exec edge or the source of a data edge - for entry-point purposes we only need "is this
	// node ever the target of an exec edge", plus "does this node itself have any incoming data
	// connection" (checked directly on the node in the caller, not via this map).
	for (const TPair<FGuid, UFlowNode*>& NodePair : Asset->GetNodes())
	{
		const UFlowNode* Node = NodePair.Value;
		if (!Node)
		{
			continue;
		}

		for (const FFlowPin& OutputPin : Node->GetOutputPins())
		{
			if (!OutputPin.IsExecPin())
			{
				continue;
			}

			const FConnectedPin Connection = Node->GetConnection(OutputPin.PinName);
			if (Connection.NodeGuid.IsValid())
			{
				OutTargets.Add(Connection.NodeGuid);
			}
		}
	}
}

void FFlowGraphSubgraphQuery::ComputeConnectedComponent(const UFlowAsset* Asset, const FGuid& StartNodeGuid, TSet<FGuid>& OutComponent)
{
	OutComponent.Reset();
	if (!Asset)
	{
		return;
	}

	// Build a full undirected adjacency list in one pass (RS12: exec + data, both directions).
	// Exec: this node -> Connection.NodeGuid. Data: Connection.NodeGuid -> this node (the connection
	// is stored on the receiving node, so its value is the upstream source).
	TMap<FGuid, TArray<FGuid>> Adjacency;
	for (const TPair<FGuid, UFlowNode*>& NodePair : Asset->GetNodes())
	{
		const FGuid& NodeGuid = NodePair.Key;
		const UFlowNode* Node = NodePair.Value;
		if (!Node)
		{
			continue;
		}

		for (const FFlowPin& OutputPin : Node->GetOutputPins())
		{
			if (!OutputPin.IsExecPin())
			{
				continue;
			}

			const FConnectedPin Connection = Node->GetConnection(OutputPin.PinName);
			if (Connection.NodeGuid.IsValid())
			{
				Adjacency.FindOrAdd(NodeGuid).Add(Connection.NodeGuid);
				Adjacency.FindOrAdd(Connection.NodeGuid).Add(NodeGuid);
			}
		}

		for (const FFlowPin& InputPin : Node->GetInputPins())
		{
			if (InputPin.IsExecPin())
			{
				continue;
			}

			const FConnectedPin Connection = Node->GetConnection(InputPin.PinName);
			if (Connection.NodeGuid.IsValid())
			{
				Adjacency.FindOrAdd(NodeGuid).Add(Connection.NodeGuid);
				Adjacency.FindOrAdd(Connection.NodeGuid).Add(NodeGuid);
			}
		}
	}

	if (!Asset->GetNodes().Contains(StartNodeGuid))
	{
		return;
	}

	// Standard BFS. OutComponent always ends up containing StartNodeGuid, even with zero edges.
	TArray<FGuid> Frontier;
	Frontier.Add(StartNodeGuid);
	OutComponent.Add(StartNodeGuid);

	while (!Frontier.IsEmpty())
	{
		const FGuid Current = Frontier.Pop();
		if (const TArray<FGuid>* Neighbors = Adjacency.Find(Current))
		{
			for (const FGuid& Neighbor : *Neighbors)
			{
				if (!OutComponent.Contains(Neighbor))
				{
					OutComponent.Add(Neighbor);
					Frontier.Add(Neighbor);
				}
			}
		}
	}
}

bool FFlowGraphSubgraphQuery::FindNodes(
	const UFlowAsset* Asset,
	const FString& TitleFilter,
	const FString& ClassFilter,
	bool bEntryPointsOnly,
	TArray<FFlowSubgraphNodeSummary>& OutResults,
	FString& OutErrorMessage)
{
	OutResults.Reset();

	if (!Asset)
	{
		OutErrorMessage = TEXT("FindNodes: Asset is null");
		return false;
	}

	// Resolve ClassFilter once (not per node) via the same resolver mutation documents use, so a
	// short name or full path behaves identically to a "Type:" line. This is the query-only variant
	// deliberately: FindNodes is read-only, and filtering for a class generated by a non-Flow
	// Blueprint is precisely how an author locates the bad nodes they need to repair. The
	// fail-closed ResolveNodeClass would make those nodes unfindable.
	UClass* ClassFilterResolved = nullptr;
	if (!ClassFilter.IsEmpty())
	{
		ClassFilterResolved = UFlowGraphImporter::ResolveNodeClassForQuery(ClassFilter);
		if (!ClassFilterResolved)
		{
			OutErrorMessage = FString::Printf(TEXT("FindNodes: Could not resolve ClassFilter: %s"), *ClassFilter);
			return false;
		}
	}

	TSet<FGuid> IncomingExecTargets;
	if (bEntryPointsOnly)
	{
		ComputeIncomingConnectionTargets(Asset, IncomingExecTargets);
	}

	TArray<FGuid> SortedNodeGuids;
	Asset->GetNodes().GenerateKeyArray(SortedNodeGuids);
	SortedNodeGuids.Sort([](const FGuid& A, const FGuid& B) { return A.ToString() < B.ToString(); });

	for (const FGuid& NodeGuid : SortedNodeGuids)
	{
		const UFlowNode* Node = Asset->GetNodes().FindRef(NodeGuid);
		if (!Node)
		{
			continue;
		}

		if (ClassFilterResolved && Node->GetClass() != ClassFilterResolved)
		{
			continue;
		}

		const FString Title = ResolveNodeTitle(Node);
		if (!TitleFilter.IsEmpty() && !Title.Contains(TitleFilter, ESearchCase::IgnoreCase))
		{
			continue;
		}

		bool bIsEntryPoint = false;
		if (bEntryPointsOnly)
		{
			// Not the target of any incoming exec edge, AND has no incoming data connection of its
			// own (data connections are stored on the receiving node, so this is a direct check).
			bool bHasIncomingData = false;
			for (const FFlowPin& InputPin : Node->GetInputPins())
			{
				if (InputPin.IsExecPin())
				{
					continue;
				}
				if (Node->GetConnection(InputPin.PinName).NodeGuid.IsValid())
				{
					bHasIncomingData = true;
					break;
				}
			}

			bIsEntryPoint = !IncomingExecTargets.Contains(NodeGuid) && !bHasIncomingData;
			if (!bIsEntryPoint)
			{
				continue;
			}
		}

		FFlowSubgraphNodeSummary& Summary = OutResults.AddDefaulted_GetRef();
		Summary.NodeGuid = NodeGuid;
		Summary.Title = Title;
		Summary.ClassPath = Node->GetClass()->GetPathName();
		Summary.bIsEntryPoint = bIsEntryPoint;
	}

	return true;
}

bool FFlowGraphSubgraphQuery::ExportSubgraph(
	UFlowAsset* Asset,
	const FGuid& StartNodeGuid,
	FString& OutExportText,
	int32& OutNodeCount,
	FString& OutErrorMessage)
{
	OutExportText.Empty();
	OutNodeCount = 0;

	if (!Asset)
	{
		OutErrorMessage = TEXT("ExportSubgraph: Asset is null");
		return false;
	}

	if (!Asset->GetNodes().Contains(StartNodeGuid))
	{
		OutErrorMessage = FString::Printf(TEXT("ExportSubgraph: StartNodeGuid %s does not resolve to a node on this asset"), *StartNodeGuid.ToString());
		return false;
	}

	TSet<FGuid> Component;
	ComputeConnectedComponent(Asset, StartNodeGuid, Component);

	OutExportText = UFlowGraphExporter::ExportFlowGraphSubsetToString(Asset, Component);
	OutNodeCount = Component.Num();
	return true;
}
