// Copyright https://github.com/MothCocoon/FlowGraph/graphs/contributors

#pragma once

#include "UObject/Interface.h"
#include "FlowDataPinGeneratorInterface.generated.h"

struct FFlowAutoDataPinsWorkingData;

// Interface for Classes that can auto-generate DataPins
UINTERFACE(MinimalAPI, NotBlueprintable, DisplayName = "Flow Data Pin Generator Interface", meta = (CannotImplementInterfaceInBlueprint))
class UFlowDataPinGeneratorInterface : public UInterface
{
	GENERATED_BODY()
};

class FLOW_API IFlowDataPinGeneratorInterface
{
	GENERATED_BODY()

public:
#if WITH_EDITOR
	virtual void AutoGenerateDataPins(FFlowAutoDataPinsWorkingData& InOutWorkingData) const = 0;	
#endif
};
