// Copyright https://github.com/MothCocoon/FlowGraph/graphs/contributors

#pragma once

#include "UObject/Interface.h"
#include "Nodes/FlowPin.h"

#include "FlowDataPinGeneratorNodeInterface.generated.h"

// Interface for special UFlowNodes that can auto-generate pins directly
UINTERFACE(MinimalAPI, NotBlueprintable, DisplayName = "Flow Data Pin Generator Node Interface")
class UFlowDataPinGeneratorNodeInterface : public UInterface
{
	GENERATED_BODY()
};

class FLOW_API IFlowDataPinGeneratorNodeInterface
{
	GENERATED_BODY()

public:
#if WITH_EDITOR
	virtual void AutoGenerateDataPins(TMap<FName, FName>& PinNameToBoundPropertyMap, TArray<FFlowPin>& InputDataPins, TArray<FFlowPin>& OutputDataPins) const = 0;
#endif
};
