// Copyright https://github.com/MothCocoon/FlowGraph/graphs/contributors
#pragma once

#include "UObject/Interface.h"
#include "Delegates/Delegate.h"
#include "StructUtils/InstancedStruct.h"

#include "FlowDataPinValueOwnerInterface.generated.h"

struct FFlowDataPinValue;
struct FFlowDataPinValueOwner;
struct FFlowAutoDataPinsWorkingData;

UINTERFACE(NotBlueprintable)
class FLOW_API UFlowDataPinValueOwnerInterface : public UInterface
{
	GENERATED_BODY()
};

class FLOW_API IFlowDataPinValueOwnerInterface
{
	GENERATED_BODY()

public:
#if WITH_EDITOR
	/* Determines if the pin's type properties (bIsInputPin, MultiType) can be modified. */
	virtual bool CanModifyFlowDataPinType() const { return true; }

	/* Determines if the bIsInputPin checkbox should be visible in the Details panel. */
	virtual bool ShowFlowDataPinValueInputPinCheckbox() const { return true; }

	/* Should the ClassFilter or EnumClass row be visible? */
	virtual bool ShowFlowDataPinValueClassFilter(const FFlowDataPinValue* Value) const { return true; }

	/* Base policy for whether the ClassFilter / Enum source can be edited. */
	virtual bool CanEditFlowDataPinValueClassFilter(const FFlowDataPinValue* Value) const { return true; }

	/* Set the delegate that forces a layout rebuild (provided by owner detail customization). */
	virtual void SetFlowDataPinValuesRebuildDelegate(FSimpleDelegate InDelegate) {}

	/* Request a details rebuild (executes delegate if bound). */
	virtual void RequestFlowDataPinValuesDetailsRebuild() {}

	/* Automatically generate data pins from FFlowDataPinValue and FFlowNamedDataPinProperty structs. */
	virtual void AutoGenerateDataPins(FFlowDataPinValueOwner& ValueOwner, FFlowAutoDataPinsWorkingData& InOutWorkingData);
#endif

	/* Advanced helper for TrySupplyDataPin, which can be overridden in subclasses to provide alternate sourcing for properties.
	* If returns true, either OutFoundProperty or OutFoundInstancedStruct is expected to carry the property value.
	* This function is used for cases like DefineProperties, Start, and blackboard lookup nodes. */
	virtual bool TryFindPropertyByPinName(
		const FName& PinName,
		const FProperty*& OutFoundProperty,
		TInstancedStruct<FFlowDataPinValue>& OutFoundInstancedStruct) const;

	static bool TryFindPropertyByPinName_Static(
		const UObject& PropertyOwnerObject,
		const FName& PinName,
		const FProperty*& OutFoundProperty,
		TInstancedStruct<FFlowDataPinValue>& OutFoundInstancedStruct);
};
