// Copyright https://github.com/MothCocoon/FlowGraph/graphs/contributors

#pragma once

#include "NativeGameplayTags.h"

FLOW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Flow_NodeDisplayStyle);
FLOW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Flow_NodeDisplayStyle_Custom);

FLOW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Flow_NodeDisplayStyle_Node);
FLOW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Flow_NodeDisplayStyle_Node_Condition);
FLOW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Flow_NodeDisplayStyle_Node_Deprecated);
FLOW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Flow_NodeDisplayStyle_Node_Developer);
FLOW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Flow_NodeDisplayStyle_Node_InOut);
FLOW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Flow_NodeDisplayStyle_Node_Latent);
FLOW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Flow_NodeDisplayStyle_Node_Logic);
FLOW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Flow_NodeDisplayStyle_Node_SubGraph);
FLOW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Flow_NodeDisplayStyle_Node_Terminal);

FLOW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Flow_NodeDisplayStyle_AddOn);
FLOW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Flow_NodeDisplayStyle_AddOn_PerSpawnedActor);
FLOW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Flow_NodeDisplayStyle_AddOn_Predicate);
FLOW_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Flow_NodeDisplayStyle_AddOn_Predicate_Composite);
